Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -2,16 +2,16 @@
 # Build a general Node.js project with npm.
 # Add steps that analyze code, save build artifacts, deploy, and more:
 # https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
-trigger: none
-# trigger:
-#   branches:
-#     exclude:
-#       - '*'
+# trigger: none
+trigger:
+  branches:
+    include:
+    - main
 
-# pr:
-#   branches:
-#     include:
-#       - main
+pr:
+  branches:
+    include:
+    - main
 
 pool:
   vmImage: ubuntu-latest
@@ -22,6 +22,53 @@ stages:
 
     jobs:
       - template: build.yml
+  
+  - stage: release
+    dependsOn: build
+    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
+    jobs:
+      - deployment: release
+        environment: production
+        pool:
+          vmImage: ubuntu-latest
+        strategy:
+          runOnce:
+            deploy:
+              steps:
+              - checkout: self
+                persistCredentials: true
+              - task: NodeTool@0
+                inputs:
+                  versionSpec: '20.x'
+                displayName: 'Install Node.js'
+              - script: |
+                  #get npm version from package.json
+                  npm_version=$(node -p "require('./package.json').version")
+                  echo "NPM version: $npm_version"
+                  
+                  #get latest tag
+                  git fetch --tags
+                  previous_version=$(git describe --tags --abbrev=0)
+                  echo "Latest git tag: $previous_version"
+
+                  previous_version_semver=${previous_version#v}
+                  
+                  if [ "$npm_version" = "$previous_version_semver" ]; then
+                    echo "Error: NPM version ($npm_version) matches latest git tag/release ($previous_version_semver). Please update version in package.json"
+                    exit 1
+                  fi
+
+                  # Create new tag and push
+                  git config user.email "pipeline@azure.devops"
+                  git config user.name "Azure Pipeline"
+                  git tag -f -a "v$npm_version" -m "Release version $npm_version"
+                  git push origin "v$npm_version"
+                  
+                  echo "running npm publish here"
+                displayName: Check version and publish package
+
+
+
 
 
 
